joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0




right_teleop_node:
  ros__parameters:
    # publish_stamped_twist: true 
    axis_linear:
      x: 3 #Left thumb stick vertical
    scale_linear:
      x: 2.0
    scale_linear_turbo:
      x: 6.0

    axis_angular:
      yaw: 2 #right thumb stick horizontal
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 4.0

    
    require_enable_button: true
    enable_button: 6 # Left shoulder button
    enable_turbo_button: 7 # Right shoulder button

left_teleop_node:
  ros__parameters:
    # publish_stamped_twist: true 
    axis_linear:
      x: 0 #Left thumb stick vertical
    scale_linear:
      x: 2.0
    scale_linear_turbo:
      x: 6.0

    axis_angular:
      yaw: 1 #right thumb stick horizontal
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 4.0

    
    require_enable_button: true
    enable_button: 6 # Left shoulder button
    enable_turbo_button: 7 # Right shoulder button