controller_manager:
  ros__parameters:
    update_rate: 30

    drone_cont:
      type: mecanum_drive_controller/MecanumDriveController

    diffdrive_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster


drone_cont:
  ros__parameters:
    use_stamped_vel: false

    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "flm_joint"
    front_right_wheel_command_joint_name: "frm_joint"
    rear_right_wheel_command_joint_name: "rlm_joint"
    rear_left_wheel_command_joint_name: "rrm_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 1.0
      sum_of_robot_center_projection_on_X_Y_axis: 1.0

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    pose_covariance_diagonal: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    twist_covariance_diagonal: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

diffdrive_cont:
  ros__parameters:
    use_stamped_vel: false
    left_wheel_names: ["frlm_joint"]
    right_wheel_names: ["frrm_joint"]

    wheel_separation: 0.40
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.02

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    